:source-highlighter: coderay

= Concordion AsciiDoc

image::https://img.shields.io/badge/license-Apache%202.0-blue.svg["Apache License 2.0", link="http://www.apache.org/licenses/LICENSE-2.0.html"]

This Concordion AsciiDoc extension is massively is under development, don't use it in production, but any contribution
is welcome.

== Introduction

http://www.methods.co.nz/asciidoc/[AsciiDoc] is a text document format for writing documentation, articles, books,
etc. AsciiDoc files can be translated to many formats including HTML, PDF. Its
http://www.methods.co.nz/asciidoc/userguide.html[AsciiDoc User Guide] is very detailed.

http://concordion.org[Concordion] is a software testing tool to create "live documentation".

This Concordion AsciiDoc extension allows you to write your Concordion specification in AsciiDoc format. This
extension is based on https://github.com/asciidoctor/asciidoctorj[AsciidoctorJ] which is a Java bindings for Asciidoctor.
http://asciidoctor.org/[AsciiDoctor] is a toolchain for converting AsciiDoc content which is written in Ruby.

The https://github.com/concordion/concordion-markdown-extension[Concordion Markdown] inspired me to write this extension.

== Motivation

To write a Concordion test in XHTML format is a little bit verbose. (This example is from the Concordion tutorial.)

[source, xml]
----
<html xmlns:concordion="http://www.concordion.org/2007/concordion">

    <head>
        <link href="../concordion.css" rel="stylesheet" type="text/css" />
    </head>

    <body>

        <h1>Splitting Names</h1>

        <p>
            To help personalise our mailshots we want to have the first name
            and last name of the customer. Unfortunately the customer data
            that we are supplied only contains full names.
        </p>

        <p>
            The system therefore attempts to break a supplied full name into
            its constituents by splitting around whitespace.
        </p>

        <div class="example">

            <h3>Example</h3>

            <p>
                The full name
                <span concordion:execute="#result = split(#TEXT)">John Smith</span>
                will be broken into first name
                <span concordion:assertEquals="#result.firstName">John</span>
                and last name
                <span concordion:assertEquals="#result.lastName">Smith</span>.
            </p>

        </div>
    </body>
</html>
----

Same test case in AsciiDoc with Concordion AsciiDoc extension.

[source,asciidoc]
----
== Splitting Names

To help personalise our mailshots we want to have the first name
and last name of the customer. Unfortunately the customer data
that we are supplied only contains full names.

The system therefore attempts to break a supplied full name into
its constituents by splitting around whitespace.

[.example]
=== Example

The full name
concordion:execute[#result = split(#TEXT), John Smith]
will be broken into first name
concordion:assertEquals[#result.firstName, John]
and last name
concordion:assertEquals[#result.lastName, Smith].
----

== Usage

With Maven use the following dependency:

[source,xml]
----
<dependency>
    <groupId>hu.jtechlog</groupId>
    <artifactId>concordion-asciidoc-extension</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
----

In Concordion test fixture use `AsciiDocConcordionExtension`:

[source,java]
----
@RunWith(ConcordionRunner.class)
@Extensions(AsciiDocConcordionExtension.class)
public class HelloWorldFixture {

    // ...
}
----

== Supported Concordion structures and commands

This examples based on the http://concordion.org/Tutorial.html[Concordion tutorial]. The Concordion AsciiDoc
Extensions use AsciiDoc macros. The format of the macro is `<name>:<target>[<attrlist>]`, where the `name` is
 `concordion`.

=== assertEquals command

Use `assertEquals` command in the following form:

[source,asciidoc]
----
concordion:assertEquals[getGreeting(), Hello World]
----

=== set command

Use `set` command in the following form:

[source,asciidoc]
----
concordion:set[#firstName, Bob]
----

=== execute command

Use `execute` command with one parameter:

[source,asciidoc]
----
concordion:execute[setGreeting(#greeting)]
----

or with two parameters:

[source,asciidoc]
----
concordion:execute[setGreeting(#TEXT), Hello]
----

=== Example div

No need for any special element, in AsciiDoctor there are two ways to assign a role attribute to a block element.
It will be compiled to CSS class in the HTML output.

Prefixing the name with a dot (`.`).

[source,asciidoc]
----
[.example]

Hello World!
----

Or specifying role attribute with `role=<name>` pattern.

[source,asciidoc]
----
[role="example"]

Hello World!
----

=== Handling unusual sentence structures

Using this macro the extension will create the `execute` command on the outer `p` element.

[source,asciidoc]
----
concordion:executeOnParagraph[#greeting = greetingFor(#firstName)]
----

=== Execute on a table

In the first row declare the `execute` command for the whole table, and `set` or `assertEquals` commands for the
columns. An `execute` attribute will be generated in the html `table` tag, and `set` or `assertEquals` attributes
will be generated in the `th` tag.

[source,asciidoc]
----
|===
| Full Name | First Name | Last Name

| concordion:executeOnTable[#result = split(#fullName)] concordion:setOnAllRows[#fullName]
| concordion:assertEqualsOnAllRows[#result.firstName]
| concordion:assertEqualsOnAllRows[#result.lastName]

| John Smith
| John
| Smith

| David Peterson
| David
| Peterson
|===
----

=== verifyRows command

Declare the `verifyRows` command in the first row of the table.

[source,asciidoc]
----
|===
| Matching Usernames

| concordion:verifyRows[#username : getSearchResultsFor(#searchString)] concordion:assertEqualsOnAllRows[#username]
| george.harrison
| ringo.starr
|===
----

=== executeOnList command

Declare the `executeOnList` command in the first item of the list. Nested lists are also supported.

[source,asciidoc]
----
|===
. concordion:executeOnList["parseNode(#TEXT, #LEVEL)"] Europe
** Austria
... Vienna
** UK
*** England
*** Scotland
** France
. Australia
|===
----

=== run command

Use `run` command in the following form:

[source,asciidoc]
----
concordion:run[HelloWorld.adoc, Hello world]
----
